In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/processed/concrete_cleaned.csv")
df

,Cement,BlastFurnaceSlag,FlyAsh,Water,Superplasticizer,CoarseAggregate,FineAggregate,Age,CompressiveStrength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1000,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1001,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1002,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1003,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1004,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [4]:
df.columns.to_list()

['Cement',
 'BlastFurnaceSlag',
 'FlyAsh',
 'Water',
 'Superplasticizer',
 'CoarseAggregate',
 'FineAggregate',
 'Age',
 'CompressiveStrength']

In [5]:
# add water and cement ratio column
df["WaterCementRatio"] = df["Water"] / df["Cement"]

# add total binder column
df["TotalBinder"] = df["Cement"] + df["BlastFurnaceSlag"] + df["FlyAsh"]

# add water and total binder ratio
df["WaterBinderRatio"] = df["Water"] / df["TotalBinder"]

# add total aggregate column
df["TotalAggregate"] = df["CoarseAggregate"] + df["FineAggregate"]

# add fine agg ratio
df["FineAggregateRatio"] = df["FineAggregate"] / df["TotalAggregate"]

# add coarse agg ratio
df["CoarseAggregateRatio"] = df["CoarseAggregate"] / df["TotalAggregate"]

# add cement ratio
df["CementRatio"] = df["Cement"] / df["TotalBinder"]

# add SCM and SCM percentage
df["SCM"] = df["BlastFurnaceSlag"] + df["FlyAsh"]
df["SCMPercentage"] = df["SCM"] / df["TotalBinder"]

# log age
df["LogAge"] = np.log1p(df["Age"])

In [6]:
df

,Cement,BlastFurnaceSlag,FlyAsh,Water,Superplasticizer,CoarseAggregate,FineAggregate,Age,CompressiveStrength,WaterCementRatio,TotalBinder,WaterBinderRatio,TotalAggregate,FineAggregateRatio,CoarseAggregateRatio,CementRatio,SCM,SCMPercentage,LogAge
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99,0.300000,540.0,0.300000,1716.0,0.393939,0.606061,1.000000,0.0,0.000000,3.367296
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89,0.300000,540.0,0.300000,1731.0,0.390526,0.609474,1.000000,0.0,0.000000,3.367296
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27,0.685714,475.0,0.480000,1526.0,0.389253,0.610747,0.700000,142.5,0.300000,5.602119
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05,0.685714,475.0,0.480000,1526.0,0.389253,0.610747,0.700000,142.5,0.300000,5.902633
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30,0.966767,331.0,0.580060,1803.9,0.457620,0.542380,0.600000,132.4,0.400000,5.888878
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28,0.649783,482.7,0.372074,1638.4,0.468933,0.531067,0.572612,206.3,0.427388,3.367296
1001,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18,0.608318,437.8,0.447693,1631.3,0.498621,0.501379,0.735952,115.6,0.264048,3.367296
1002,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70,1.297643,396.5,0.486003,1672.4,0.466396,0.533604,0.374527,248.0,0.625473,3.367296
1003,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77,1.103708,345.8,0.507808,1778.5,0.443576,0.556424,0.460093,186.7,0.539907,3.367296
1004,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40,0.768877,439.7,0.456220,1626.0,0.468327,0.531673,0.593359,178.8,0.406641,3.367296

In [7]:
df.to_csv(r"../data/processed/concrete_featured.csv", index=False)